### ISSUE TITLE
Timeout error when debugging with protocol="inspector"

### ISSUE THREAD

**Issue by kfrederix** [jsreport/jsreport-core#22] opened 2017-10-17 10:44 UTC
I'm consistently getting timeout errors during render() while debugging my application using vscode with protocol "inspector".

The error is always the same:
```
OperationalError {
    cause: Error: Timeout error during executing script
    ...
}
```
```
at: script-manager\lib\manager-processes.js:24:8
    at ontimeout (timers.js:469:11)
    at Timer.unrefdHandle (timers.js:580:5)
```

Debugging with legacy protocol works without problem, but that is not supported anymore with node versions >= v8.0.

P.S. just running the application (with node v8.6.0) works fine... no problem. Only getting this error when trying to debug.

**Comment by bjrmatos** [comment] 2017-10-17 15:14
hi! my first guest is that you are using the default [tasks](https://jsreport.net/learn/configuration#script-tasks) strategy (`dedicated-process`) which spawns a new child process for template rendering and script execution. when using child process `node --inspect` protocol does not work out of the box. for example if you run a node.js app with `node --inspect server.js` and that app spawns a child process eventually you will see a message like this in the console `Starting inspector on 127.0.0.1:9229 failed: address already in use`, which means that node.js fails because it is trying to use the same debug port (`9229`) for two processes (the main one and the child), this is the cause that makes jsreport to timeout.

<img width="946" alt="captura de pantalla 2017-10-17 a las 10 01 46 a m" src="https://user-images.githubusercontent.com/4262050/31672501-58387838-b322-11e7-868f-3902891265ba.png">

you have two options to solve this and let you debug your jsreport app normally:

- use `--inspect=0` instead of just `--inspect`. example command for a node.js app `node --inspect=0 server.js`, passing the value of `0` tells node.js that it should use a random debug port number for each process that tries to start (including the main one), the downside of this method is that i'm not sure if vscode have a way to automatically know what are those randome debug port numbers used in the app. also, as far as i can remember this works in node.js 8, not sure if it was introduced in node.js 6 too.
- your other option is to change `tasks.strategy` to `in-process` just when you need to debug your app. `in-process` means that jsreport will just run template rendering and scripts in the same process of the main one instead of creating child processes, this will let you debug your app normally.

i'm closing the issue since there is directly nothing that we can do about this (because this should be handled in user land) but if you have other comments feel free to keep the conversation. hope that this information helps you.

**Closed by bjrmatos** 2017-10-17 15:14 UTC

**Comment by pofider** [comment] 2017-10-17 15:25
Hm. For me the debugging in VS Code with `inspector` doesn't even start. I personally don't use debugging at all when developing in node.

However the issues could be that we by default spawn child processes which are used for templating engines evaluation in sandbox. You could try to change the configuration and run templating engine directly in the same process
```js
{
   ...
   "tasks": { "strategy": "in-process" }
   ...
```

or perhaps increase the timeout for templating engines using

```js
{
   "tasks": { "timeout": 6000000 }
}
```

**Comment by kfrederix** [comment] 2017-10-18 07:52
Thanks @bjrmatos, @pofider for such in-depth responses !
Debugging with `tasks.strategy` set to `in-process` works like a charm.

**Comment by Bene-Graham** [comment] 2018-01-17 18:36
@pofider Where about do you put `"tasks": { "strategy": "in-process" }`?

**Comment by pofider** [comment] 2018-01-18 18:32
@Bene-Graham Check [readme here](https://github.com/jsreport/jsreport-core#configuration) to see how you can pass configuration to jsreport.

**Comment by Bene-Graham** [comment] 2018-02-14 14:46
@pofider Worked like a charm.

Thanks

**Comment by gustavomassa** [comment] 2018-07-30 18:41
Using "tasks": { "strategy": "in-process" } doesn't work for me, same inspector error message.

**Comment by pofider** [comment] 2018-07-30 18:46
in v2 it is `"templatingEngines":{ "strategy": "in-process" }"`

**Comment by gustavomassa** [comment] 2018-07-30 19:04
@pofider
You are right, using templatingEngines works fine. I'm using typescript with the latest @types/jsreport-core version 1.5.1, the config interface is outdated.
Also the jsreport-express options are outdated from github readme: https://github.com/jsreport/jsreport-express

This is the correct one:
extensions: {
                    express: { app: app, server: server },
                },
                appPath: '/api/v1/reporting'
};

I think all jsreport extensions docs(Readme) should be reviewed and updated if needed.

Thanks!

**Comment by bjrmatos** [comment] 2018-07-30 21:51
> You are right, using templatingEngines works fine. I'm using typescript with the latest @types/jsreport-core version 1.5.1, the config interface is outdated.

yes, we recently landed v2, so i guess it is matter of time for the types to be updated, we don't maintain the types as part of our release process, the current types was a collaboration of another user so hopefully another TS user can collaborate with the updates, if not we will look into it but as part of future tasks.



> Also the jsreport-express options are outdated from github readme: jsreport/jsreport-express

i saw that there was just one line missing to update, it is updated now, thanks for noticing it
