### ISSUE TITLE
JSreport failed to start on CentOS 7.6

### ISSUE THREAD

**Issue by yami12376** [jsreport/jsreport-core#46] opened 2019-04-19 14:31 UTC
I am doing steps from: https://jsreport.net/learn/centos
but i get an error:

# jsreport start

> An error has occurred when trying to initialize jsreport (2). Error when loading extension chrome-pdf
> Error: Cannot find module 'puppeteer'

**Then again while trying additional step:**

# npm -v
5.6.0

# npm install puppeteer jsreport-chrome-pdf

> puppeteer@1.14.0 install /opt/jsreportapp/node_modules/puppeteer
> node install.js

sh: node: command not found
npm WARN jsreport-server@ No description
npm WARN jsreport-server@ No repository field.
npm WARN jsreport-server@ No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! puppeteer@1.14.0 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the puppeteer@1.14.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-19T14_10_25_149Z-debug.log

**Comment by bjrmatos** [comment] 2019-04-19 14:57
duplicate of jsreport/jsreport#538

**Closed by bjrmatos** 2019-04-19 14:57 UTC
